package Modules.Interactions.Commands;

public enum GameCommand implements Command {
    showTime,
    showDate,
    showDateTime,
    showDayOfWeek,
    cheatAdvanceTime,
    cheatAdvanceDate,
    season,
    nextTurn,
    forceTerminate,
    exitGame,
    startNewGame,
    walk,
    printMap,
    helpPrintMap,
    weather,
    weatherForecast,
    cheatWeatherForecast,
    cheatThor,
    buildGreenHouse,
    showEnergy,
    cheatEnergy,
    energyUnlimited,
    inventoryShow,
    inventoryTrash,
    toolEquip,
    toolCurrentShow,
    toolShowAvailable,
    toolUpgrade,
    toolUse,
    exit;
}
